### ISSUE TITLE
请求角色列表出现问题：请勿修改设备本地时间 签到失败: 'data'

### ISSUE THREAD

**Issue by Charonics** [Zerolouis/skyland_auto_sign_qinglong#7]
执行时遇到问题，请求角色列表出现问题：请勿修改设备本地时间，签到失败: 'data'；
ERROR:root:请求角色列表出现问题：请勿修改设备本地时间
ERROR:root:签到完全失败了！: 
Traceback (most recent call last):
  File "/ql/data/scripts/skyland_auto_check.py", line 270, in start
    do_sign(cred)
  File "/ql/data/scripts/skyland_auto_check.py", line 237, in do_sign
    characters = get_binding_list(cred)
  File "/ql/data/scripts/skyland_auto_check.py", line 223, in get_binding_list
    for i in resp['data']['list']:
KeyError: 'data'

**Comment by Zerolouis** [comment]
时间戳错误，检查下服务器时间，青龙面板是否托管在境外了(不确定有没有影响)
可以描述下青龙面板的部署情况吗

**Comment by xxyz30** [comment]
> 时间戳错误，检查下服务器时间，青龙面板是否托管在境外了(不确定有没有影响) 可以描述下青龙面板的部署情况吗

很经典的错误。系统时间快于服务器的时间就会这样。而yj没有啥find_server_time的接口，部分设备就会这样子。
我在测试的时候就经常遇到这个问题，所以我故意在代码里减了两秒（
